import { Header } from "@/components/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* welcome to habitopia */}
        <h1 className="text-6xl text-center mt-20">
          <span className="text-red-500">welcome</span> to{" "}
          <span className="text-blue-500">habit</span>
          <span className="text-green-500">opia</span>
        </h1>
        <Header />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
